### ISSUE TITLE
Dark mode css?

### ISSUE THREAD

**Issue by galtenberg** [ingmarh/scroll-shadow-element#3]
Greetings... This component has been lovely to use, thank you for building it.

For adding dark-mode shadowing to my app (lighter shadows), I've tried the usual `@media (prefers-color-scheme: dark) { ... }` css, trying on both the component and the `<p>` element it's applied to, and I haven't stumbled on the right combination.

Do you have any recommendation?

**Comment by ingmarh** [comment]
Hi @galtenberg,

I’m glad to hear that the component is useful for you, and thanks for your question.

You can [use CSS Custom Properties to change the appearance of the shadows](https://github.com/ingmarh/scroll-shadow-element#configuration). You could copy the default values and adjust them so that the shadows look good with the dark scheme colors of your app. Any valid [`background-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) value should work for the shadow custom properties.

Here is an example using the default appearance but with adapted, lighter linear color stop, `rgba(255,255,255,.2)`:

```css
@media (prefers-color-scheme: dark) {
  :root {
    --scroll-shadow-top: radial-gradient(farthest-side at 50% 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-bottom: radial-gradient(farthest-side at 50% 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-left: radial-gradient(farthest-side at 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-right: radial-gradient(farthest-side at 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
  }

  .container {
    background: #021d1c;
    color: #efefef;
    /* ... */
  }
}
```

```html
<scroll-shadow>
  <div class="container">Content</div>
</scroll-shadow>
```

Note: The custom properties need to be applied to the `scroll-shadow` element, and not to the actual scrolling/overflowing child element. In the above example, instead of `:root {  }`, you could also use the `scroll-shadow {  }` selector to set them, but not `.container {  }`.

Of course, the right color combination depends on the dark scheme colors of your app, so when taking the above example you might need to adjust the color stop value in order that it looks good for your use case. I hope that helps.

**Comment by galtenberg** [comment]
@ingmarh Thank you so much for the reply –

My issue was actually that I believe the variables can only be set once. This wasn't working:

```css
scroll-shadow {
  --scroll-shadow-top: radial-gradient(farthest-side at 50% 0%, rgba(0,0,0,.2), rgba(0,0,0,0));
  --scroll-shadow-bottom: radial-gradient(farthest-side at 50% 100%, rgba(0,0,0,.2), rgba(0,0,0,0));
  --scroll-shadow-left: radial-gradient(farthest-side at 0%, rgba(0,0,0,0), rgba(0,0,0,0));
  --scroll-shadow-right: radial-gradient(farthest-side at 100%, rgba(0,0,0,0), rgba(0,0,0,0));
}

@media (prefers-color-scheme: dark) {
  scroll-shadow {
    --scroll-shadow-top: radial-gradient(farthest-side at 50% 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-bottom: radial-gradient(farthest-side at 50% 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-left: radial-gradient(farthest-side at 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-right: radial-gradient(farthest-side at 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
  }
}
```

The dark mode settings were never used. 

After your post here, an obvious solution came to mind:

```css
@media (prefers-color-scheme: light) {
  scroll-shadow {
    --scroll-shadow-top: radial-gradient(farthest-side at 50% 0%, rgba(0,0,0,.2), rgba(0,0,0,0));
    --scroll-shadow-bottom: radial-gradient(farthest-side at 50% 100%, rgba(0,0,0,.2), rgba(0,0,0,0));
    --scroll-shadow-left: radial-gradient(farthest-side at 0%, rgba(0,0,0,0), rgba(0,0,0,0));
    --scroll-shadow-right: radial-gradient(farthest-side at 100%, rgba(0,0,0,0), rgba(0,0,0,0));
  }
}

@media (prefers-color-scheme: dark) {
  scroll-shadow {
    --scroll-shadow-top: radial-gradient(farthest-side at 50% 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-bottom: radial-gradient(farthest-side at 50% 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-left: radial-gradient(farthest-side at 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-right: radial-gradient(farthest-side at 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
  }
}
```

😄 Which works just fine.

**Comment by ingmarh** [comment]
I see!

Actually, your first example should also work (just tested it to be sure). Could it be that the order of the rulesets were swapped when the styles are loaded in the browser? If the media query ruleset is not last, then the other ruleset wins for dark mode. It should not matter if you only overwrite for dark mode and leave the component default styles for light mode. Then, you could omit the light mode ruleset–for example:

```css
@media (prefers-color-scheme: dark) {
  scroll-shadow {
    --scroll-shadow-top: radial-gradient(farthest-side at 50% 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-bottom: radial-gradient(farthest-side at 50% 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-left: radial-gradient(farthest-side at 0%, rgba(255,255,255,.2), rgba(0,0,0,0));
    --scroll-shadow-right: radial-gradient(farthest-side at 100%, rgba(255,255,255,.2), rgba(0,0,0,0));
  }
}
```

In any case, good that you found a solution for your use case. 👍
